### ISSUE TITLE
Change Zaïre to DR Congo, retain code ZAI

### ISSUE THREAD

**Issue by rg02kg** [tdwg/geoschemes#17] opened 2021-08-19 11:18 UTC
Zaïre has now long changed to Democratic Republic of the Congo so we could use the long version or "DR Congo" (my preference) to distinguish it from "Congo" whose official name is Republic of the Congo.
Retain code ZAI as it is clearly distinct from CON.

**Comment by PacoPando** [comment] 2021-08-24 13:02
I agree with this proposal. Then only the name of the level 3 code ZAI ,and the name of the level 4 unit ZAI-OO change

**Comment by RRKlopper** [comment] 2021-11-24 13:30
I agree to change the name to DR Congo but to keep the ZAI code.

**Comment by PacoPando** [comment] 2022-06-24 07:59
Changes committed in working docs.

**Comment by MarcSosef** [comment] 2024-11-04 15:33
Changing Zaire to DR Congo is a good thing (Zaire also being a politically sensitive name since it is linked to the former dictator Mobutu...), but there is a related problem with the abbreviated name Congo (for Republic of Congo). As Editor of the Flore d'Afrique centrale, I regularly come across errors caused by others interpreting "Congo" as referring to the country DR Congo (in IPNI, POWO, WFO, but also in label transcription), or the other way around. I therefore argue to also adjust "Congo" to "Rep. Congo", but am in for any better alternative.

**Comment by MarcSosef** [comment] 2024-11-04 15:55
Hi Rafael,
Nice to see you join in on this discussion. Surely, POWO is consistent in the usage of the two distinct country names. What I notice sometimes is that authors of literature on which POWO based their distributions made errors, mixing up the two countries. Hence I argue that "Congo" is insufficiently different from "DR Congo" to avoid such, and hope we can find a better wording to distinguish the two, leading to less errors.
kind regards,
Marc

**Comment by rg02kg** [comment] 2024-11-04 16:15
Dear Mark,
Rep.Congo is already confusing as I thought you meant that as an alternative for DR Congo.
Congo has been known as Congo for a long time, so I’m not to keen to change that for TDWG.
Many use Congo(Brazzaville) and Congo(Kinshasa) but I’m not sure what the Congolese think of that.

Best wishes,
Rafaël <https://www.kew.org/science/who-we-are-and-what-we-do/people/rafa%C3%ABl-h-a-govaerts>

**Comment by PacoPando** [comment] 2024-11-06 14:52
Thank you to you too for this enlightening discussion.

**Comment by MarcSosef** [comment] 2024-11-06 15:05
I would support a proposal to change the abbreviated names of the two countries to Congo-Brazzaville, or Congo (Brazzaville), and Congo-Kinshasa, or Congo (Kinshasa). Indeed, it would be nice to have the opinions of some persons from the region, but I doubt if there are any representatives available within TDWG? I can ask some colleagues myself if there is further support for this alternative?
kind regards,
Marc

**Comment by PacoPando** [comment] 2024-11-06 15:09
Thank you to you two for this enlightening discussion. I consider that this issue deserves further attention, so I have re-opened it.

**Comment by PacoPando** [comment] 2024-11-06 15:31
Changing the codes is always more problematic than modifying the names (because of the back-compatibility issues these may create) . It is important to remember that the names of the countries do not necessarily have to match their official names. Additionally, the TDWG strives to avoid using ISO codes for the countries involved in the units to prevent any confusion between ISO and TDWG codes

**Comment by MarcSosef** [comment] 2024-11-07 06:43
OK, I checked with several colleagues from both countries, and they all prefer DR Congo along with Congo for the two countries. Basically, this means that the decision made before, to change Zaïre to DR Congo, can stay as is, and no further adjustment is needed. Sorry to have brought this up again, but it is good to know that there is support from the Plant taxonomists in the region.
kind regards,
Marc

**Comment by PacoPando** [comment] 2024-11-07 07:29
Hi Marc, On the contrary, thanks to you for checking this up with colleagues in the region that is important. Thanks to Rafaël  too. Then I close this issue again.

**Closed** 2024-11-07 07:30 UTC
